spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: onboarding-service
          uri: ${ONBOARDING_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/accounts/**, /api/onboarding/**, /api/customer/**
        - id: bills-service
          uri: ${BILLS_SERVICE_URL:http://localhost:8200}
          predicates:
            - Path=/api/bills/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${RAILWAY_STATIC_URL:localhost}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

#  instance:
#    hostname: localhost
