spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: onboarding-service
          uri: ${ONBOARDING_SERVICE_URL}
          predicates:
            - Path=/api/accounts/**, /api/onboarding/**, /api/customer/**
        - id: bills-service
          uri: ${BILLS_SERVICE_URL}
          predicates:
            - Path=/api/bills/**

server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    enabled: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG